const InventoryTypes = {
  READ_ITEMS_PENDING: 'READ_ITEMS_PENDING',
  READ_ITEMS_SUCCEEDED: 'SAVE_ITEMS_SUCCEEDED',
  READ_ITEMS_FAILED: 'READ_ITEMS_FAILED',
  READ_ITEMS_IDLE: 'READ_ITEMS_IDLE',
  READ_INVENTORY_PENDING: 'READ_INVENTORY_PENDING',
  READ_INVENTORY_SUCCEEDED: 'SAVE_INVENTORY_SUCCEEDED',
  READ_INVENTORY_FAILED: 'READ_INVENTORY_FAILED',
  READ_INVENTORY_IDLE: 'READ_INVENTORY_IDLE'
}

export default InventoryTypes;