const ItemsTypes = {
  READ_ITEMS_PENDING: 'READ_ITEMS_PENDING',
  READ_ITEMS_SUCCEEDED: 'SAVE_ITEMS_SUCCEEDED',
  READ_ITEMS_FAILED: 'READ_ITEMS_FAILED',
  READ_ITEMS_IDLE: 'READ_ITEMS_IDLE',
}

export default ItemsTypes;