inventory:
- id: A429
  name: Inventory A429
  stock: 145
  total: 200

- id: A342
  name: Inventory A342
  stock: 293
  total: 490

- id: A235
  name: Inventory A235
  stock: 0
  total: 0

- id: B535
  name: Inventory B535
  stock: 0
  total: 0

- id: B020
  name: Inventory B020
  stock: 0
  total: 0

items:
- id: II06343
  inventory: A429
  name: Foo
  status: in-progress
  price: 23
  stock: 4
  total: 10

- id: II22130
  inventory: A429
  name: Bar
  status: on-hold
  price: 60
  stock: 2
  total: 10

- id: II73495
  inventory: A429
  name: Baz
  status: in-progress
  price: 35
  stock: 44
  total: 50

- id: II63994
  inventory: A429
  name: Qux
  status: on-hold
  price: 33
  stock: 34
  total: 58

- id: II35029
  inventory: A342
  name: Omn
  status: on-hold
  price: 5
  stock: 1
  total: 27

- id: II12500
  inventory: A342
  name: Nom
  status: in-progress
  price: 27
  stock: 40
  total: 40

- id: II21004
  inventory: A342
  name: Hum
  status: on-hold
  price: 21
  stock: 4
  total: 20

- id: II63049
  inventory: A429
  name: Vim
  status: in-progress
  price: 10
  stock: 7
  total: 30